twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    
    globals:
        image_dir: '/images/product'
        cartHandler: '@App\Service\CartHandler'
when@test:
    twig:
        strict_variables: true